### ISSUE TITLE
Error: spawn slimrb ENOENT

### ISSUE THREAD

**Issue by bORm** [cognitom/gulp-slim#34]
```
gulp.task 'slim', ->
    gulp.src './assets/slim/*.slim'
    .pipe slim()
    .pipe gulp.dest './public/html/'
```

```
spawn called
{ '0': 'slimrb', '1': [ '-s' ], '2': {} }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn slimrb ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
  at child_process.js:1144:20
  at process._tickCallback (node.js:355:11)

```

**Comment by bORm** [comment]
```
sudo gem install slim
```
Close

**Comment by mvelebit** [comment]
Why does ending a user session invoke this error? I mean I have to manually call  `sudo gem install slim
` each time i ssh onto the machine, which is weird. Any clues?

**Comment by juanpablob** [comment]
Same here! Got the same problem as @mvelebit — Any ideas how to fix this issue?
