### ISSUE TITLE
no writecb in Transform class

### ISSUE THREAD

**Issue by viktor-yakubiv** [cognitom/gulp-slim#35]
I have an issue with compiling slim.

My code looks like this:
```javascript
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')({scope: ['devDependencies']});

gulp.task('html', function () {
  return gulp.src('slim/**/*.slim')
    .pipe(plugins.slim())
    .pipe(gulp.dest('dist/views'));
});
```

Error goes here:
```bash
[19:07:24] Starting 'html'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (D:\Develop\bootstrap-wdk\node_modules\gulp-slim\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:95:33)
    at TransformState.afterTransform (D:\Develop\bootstrap-wdk\node_modules\gulp-slim\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at Socket.<anonymous> (D:\Develop\bootstrap-w
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

I think this was resolved here, but I don't understand it.
https://github.com/sindresorhus/gulp-esnext/issues/8

**Comment by yozzh** [comment]
Can you show me your slim-file?

**Comment by viktor-yakubiv** [comment]
It look like this.
```slim
<!DOCTYPE html>
html lang="en"
head
  meta charset="UTF-8"/
  title Document
body

```
I have add some changes and don't remember what it was. There was autogenerated slim code by Emmet (command "!" without braces).

**Comment by yozzh** [comment]
You have a syntax errors in your slim file:
1. Slim generates doctype with this construction:
`doctype html`
2. You have wrong indentation of head and body tags. They must be inside html tag.
Try to fix it and reply with results.

**Comment by viktor-yakubiv** [comment]
No. It is not important.
Slim code is valid. Bad indented code will compiles with another nesting only, e.x.:
```slim
<!doctype html>
html
head
body
```
compiles to
```html
<!DOCTYPE html>
<html></html>
<head></head>
<body></body>
```
I tried to run `slimrb *` from slim directory and have no errors, good output. When I changes my file, it have no errors, just compile with some unexpectedly.

I have test this task with different code. For example:
```slim
doctype html
html lang="en"
```
This code is valid slim, but causes the same error.

**Comment by jossiwolf** [comment]
Same issue here, what can I do?

```
<!doctype html>
html
head
body
```

This code is working fine.

**Comment by ekiziltas** [comment]
Same issue
